GET http://localhost:3001/api/ping
###
GET http://localhost:3001/api/diagnoses
###
GET http://localhost:3001/api/patients
###

# POST http://localhost:3001/exercises HTTP/1.1
# content-type: application/json

# {
#     "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
#     "target": "2.5"
# }

###
