GET http://localhost:3001/api/ping
###
GET http://localhost:3001/api/diagnoses
###
GET http://localhost:3001/api/patients
###

POST http://localhost:3001/api/patients HTTP/1.1
content-type: application/json

{
  "name": "Jenniina",
  "ssn": "16",
  "dateOfBirth": "2002-03-03",
  "occupation": "CDO",
  "gender": "female"
}

###
